---
- name: Neustarten des Hosts und Überprüfen der Verfügbarkeit
  hosts: all
  become: yes  # Verwende "become" für erhöhte Rechte
  tasks:
    - name: Neustart des Hosts
      command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true
      register: reboot_command

    - name: Warte 10 Sekunden, um den Neustart zu ermöglichen
      pause:
        seconds: 3

    - name: Überprüfe, ob der Host wieder verfügbar ist
      wait_for_connection:
        delay: 3
        timeout: 300

    - name: Bestätige, dass der Host wieder online ist
      ping:
