---
- name: Neustarten des Hosts
  hosts: web_servers
  become: yes  # Verwende "become" für erhöhte Rechte
  tasks:
    - name: Neustart des Hosts
      command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true
      register: reboot_command

    - name: Warte 10 Sekunden, um den Neustart zu ermöglichen
      pause:
        seconds: 10

    - name: Überprüfe, ob der Host wieder verfügbar ist (wiederhole alle 5 Sekunden)
      retries: 60
      delay: 5
      until: result is succeeded
      block:
        - name: Überprüfe, ob der Host wieder verfügbar ist
          wait_for:
            host: "{{ inventory_hostname }}"
            port: 22
            state: started
            timeout: 1
          register: result
          ignore_errors: true

    - name: Bestätige, dass der Host wieder online ist
      ping:
