---
- name: Reboot the host and check availability
  hosts: all
  become: yes  # Use "become" to gain elevated privileges
  tasks:
    - name: Reboot the host
      command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true
      register: reboot_command

    - name: Wait 10 seconds to allow the reboot to initiate
      pause:
        seconds: 10

    - name: Check if the host is available
      wait_for_connection:
        delay: 3
        timeout: 300

    - name: Confirm that the host is back online
      ping:
