---
- name: Hosts shutdown
  hosts: web_servers
  become: yes
  tasks:
    - name: Host shutdown
      command: /sbin/shutdown -h now
      async: 1
      poll: 0
      ignore_errors: true
      register: shutdown_command

    - name: acknowledge
      debug:
        msg: "Host {{ inventory_hostname }} was shut down"
