---
- name: Speedtest ausführen und Ergebnis anzeigen
  hosts: speedtest
  become: yes
  tasks:
    - name: Speedtest ausführen
      command: speedtest --format=json
      register: speedtest_result

    - name: Speedtest Ergebnis anzeigen
      debug:
        msg: "{{ speedtest_result.stdout }}"
