---
- name: Speedtest ausführen und Ergebnis speichern
  hosts: speedtest
  become: yes
  tasks:
    - name: Aktuelles Datum und Uhrzeit erfassen
      set_fact:
        # Erfasst Datum und Uhrzeit in den gewünschten Formaten
        formatted_date: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%S') | strftime('%d-%m-%Y') }}"
        formatted_time: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%S') | strftime('%H-%M') }}"

    - name: Speedtest im JSON-Format ausführen und Ergebnis in Datei speichern
      shell: speedtest --format=json > /tmp/speedtest_{{ formatted_date }}_{{ formatted_time }}.json
      register: speedtest_result
      async: 60
      poll: 0

    - name: Auf den Abschluss des Speedtests warten
      async_status:
        jid: "{{ speedtest_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 15
      delay: 3

    - name: Ergebnis aus der JSON-Datei lesen
      command: cat /tmp/speedtest_{{ formatted_date }}_{{ formatted_time }}.json
      register: speedtest_output
      when: job_result.finished

    - name: JSON-Daten filtern
      set_fact:
        filtered_result: >-
          {{
            (speedtest_output.stdout | from_json) |
            dict2items |
            selectattr('key', 'in', ['download', 'server', 'upload']) |
            items2dict
          }}

    - name: Gefiltertes Speedtest Ergebnis anzeigen
      debug:
        msg: "{{ filtered_result | to_json }}"
      when: filtered_result is defined
