---
- name: Speedtest und JSON-Daten modifizieren
  hosts: speedtest
  vars:
    # Pfad zur Z채hlerdatei
    counter_file: "/tmp/speedtest.txt"
  
  tasks:
    - name: F체hre den Speedtest aus und speichere die Daten als JSON
      command: speedtest --json
      register: speedtest_result
      async: 300  # 5 Minuten Zeitlimit f체r die Async-Aufgabe
      poll: 10    # Alle 10 Sekunden nach dem Status fragen

    - name: Warten, bis der Speedtest abgeschlossen ist
      async_status:
        jid: "{{ speedtest_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30  # Anzahl der Versuche
      delay: 3    # Wartezeit zwischen den Versuchen in Sekunden

    - name: Zeige das rohe JSON-Ergebnis
      debug:
        msg: "{{ speedtest_result.stdout }}"

    - name: Modifiziere die JSON-Daten
      set_fact:
        modified_speedtest_data: "{{ speedtest_result.stdout | from_json | json_query('{"download": download.bandwidth, "upload": upload.bandwidth, "timestamp": timestamp}') }}"

    - name: Speichere die modifizierten JSON-Daten in einer Datei
      copy:
        content: "{{ modified_speedtest_data | to_json | indent(2) }}"
        dest: "/path/to/speedtest_{{ current_number }}.json"

    - name: Update den Z채hlerstand
      copy:
        content: "{{ current_number }}"
        dest: "{{ counter_file }}"
